In [1]:
import numpy as np

In [2]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

<h3 style='color:blue'>Implement Mean Absolute Error</h3>

In [3]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [4]:
float(mae(y_predicted, y_true))

Total error is: 2.5
Mean absolute error is: 0.5


0.5

**Implementing Using Numpy**

In [5]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [6]:
float(np.mean(np.abs(y_predicted-y_true)))

0.5

In [7]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [8]:
float(mae_np(y_predicted, y_true))

0.5

<h3 style='color:blue'>Implement Log Loss or Binary Cross Entropy</h3>

In [9]:
np.log([0])

C:\Users\user\AppData\Local\Temp\ipykernel_3328\262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [10]:
epsilon = 1e-15

In [11]:
np.log([1e-15])

array([-34.53877639])

In [12]:
y_predicted

array([1, 1, 0, 0, 1])

In [13]:
y_predicted_new = [float(max(i, epsilon)) for i in y_predicted]
y_predicted_new

[1.0, 1.0, 1e-15, 1e-15, 1.0]

In [14]:
1-epsilon

0.999999999999999

In [15]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [17]:
y_predicted_new = np.array(y_predicted_new)

In [18]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [19]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

np.float64(17.2696280766844)

In [20]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [21]:
log_loss(y_true, y_predicted)

np.float64(17.2696280766844)

<h3 style='color:blue'>Implement Mean Squared error</h3>

In [22]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [23]:
def mse(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += (yt-yp)**2
    print("Total Squared Error:",total_error)
    mse = total_error/len(y_true)
    print("Mean Squared Error:",mse)
    return mse

In [24]:
mse(y_true, y_predicted)

Total Squared Error: 1.83
Mean Squared Error: 0.366


np.float64(0.366)

In [25]:
np.mean(np.square(y_true-y_predicted))

np.float64(0.366)

<h3 style='color:blue'>Implement Categorical Cross Entropy</h3>

In [30]:
import numpy as np
import math

y_true = np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1]
])

y_predicted = np.array([
    [0.8,0.1,0.1],
    [0.2,0.7,0.1],
    [0.1,0.2,0.7]
])

def categorical_cross_entropy(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        for i in range(len(yt)):
            total_error += -(yt[i] * math.log(yp[i]))
    print("Total Error:", total_error)
    cce = total_error / len(y_true)
    print("Categorical Cross Entropy:", cce)
    return cce

categorical_cross_entropy(y_true, y_predicted)

Total Error: 0.9364934391916746
Categorical Cross Entropy: 0.3121644797305582


np.float64(0.3121644797305582)

<h3 style='color:blue'>Implement Sparse Categorical Cross Entropy</h3>

In [31]:
import numpy as np
import math

y_true = np.array([0,1,2])

y_predicted = np.array([
    [0.8,0.1,0.1],
    [0.2,0.7,0.1],
    [0.1,0.2,0.7]
])

def sparse_categorical_cross_entropy(y_true, y_predicted):
    total_error = 0
    for i in range(len(y_true)):
        total_error += -math.log(y_predicted[i][y_true[i]])
    print("Total Error:", total_error)
    scce = total_error / len(y_true)
    print("Sparse Categorical Cross Entropy:", scce)
    return scce

sparse_categorical_cross_entropy(y_true, y_predicted)

Total Error: 0.9364934391916746
Sparse Categorical Cross Entropy: 0.3121644797305582


0.3121644797305582